config/routes.rb
Rails.application.routes.draw do
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  get "admin" => "admin#index"

  resources :locations
  resources :cohorts
  resources :assignments
  resources :submissions
  resources :users
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#index'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	has_many :comments, as: :commentable
	has_many :submissions
	belongs_to :user
	belongs_to :cohort

	accepts_nested_attributes_for :comments
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

	def index
		@assignments = Assignment.all
	end

	def new
		@new_assignment = Assignment.new
	end

	def create
		@user = current_user
		if @user.admin == true
			@new_assignment = Assignment.new(assignment_params)
			if @new_assignment.save
				redirect_to assignments_path
			else
				redirect_to :new
			end
		else
			redirect_to :back, notice: "Access denied.  Only administrators may view submissions."
		end
	end

	def edit
		@assignment = Assignment.find(params[:id])
	end

	def update
		@assignment = Assignment.find(params[:id])
		if @assignment.update_attributes(assignment_params)
			redirect_to assignments_path
		else
			redirect_to :edit
		end
	end

	def destroy
		@assignment = Assignment.find(params[:id])
		if @assignment.destroy
			redirect_to assignments_path
		else
			redirect_to assignments_path
		end
	end

	def show
		@assignment = Assignment.find(params[:id])
		@new_comment = Comment.new
	end

	private

	def assignment_params
		params.require(:assignment).permit(:title, :description, :due_date, :attachment, :user_id, :created_at, :updated_at, :cohort_id, commentable_attributes:[:content])
	end

end

app/views/assignments/edit.html.haml
%br
EDIT ASSIGNMENT
= form_for @assignment, method: :put do |f|
	TITLE:
	= f.text_field :title
	DESCRIPTION:
	= f.text_field :description 
	DEADLINE:
	= f.date_select :due_date
	COHORT:
	= f.select :cohort_id, Cohort.all.collect {|c| ["#{c.season}, #{c.course}", c.id]}
	%br
	%br
	= f.submit "SUBMIT CHANGES"

	= form_for @assignment, method: :delete do |f|
		= f.submit "REMOVE ASSIGNMENT", method: :delete

app/views/assignments/index.html.haml
%br
%h3 ACTIVE ASSIGNMENTS
%br
- @assignments.each do |assignment|
	%a{href: "/assignments/#{assignment.id}"} #{assignment.title}, #{assignment.due_date}
	%br
	= button_to "EDIT", url: "/assignments/#{assignment.id}/edit"
%br
= button_to "CREATE NEW ASSIGNMENT", new_assignment_path, method: :get

app/views/assignments/new.html.haml
%br
%h3 ADD NEW ASSIGNMENT
= form_for Assignment.new, method: :post do |f|
	TITLE:
	= f.text_field :title
	DESCRIPTION:
	= f.text_field :description 
	DEADLINE:
	= f.date_select :due_date
	COHORT:
	= f.select :cohort_id, Cohort.all.collect {|c| ["#{c.season}, #{c.course}", c.id]}
	%br
	%br
	= f.submit "SUBMIT ASSIGNMENT"

app/views/assignments/show.html.haml
%h1 #{@assignment.title}
%h3 DUE: #{@assignment.due_date}
= "#{@assignment.cohort.season}, #{@assignment.cohort.course}"
%br
= @assignment.description
%br
%br
= button_to "SUBMIT TO ASSIGNMENT", new_submission_path, method: :get

%hr

%h3 STUDENT SUBMISSIONS

- @assignment.submissions.each do |a|
	%a{href: "/users/#{a.user.id}"} #{a.user.name}
	%br
	%a{href: "/submissions/#{a.id}"} #{a.title}
	%br
	= a.description
	%br
	%br

%h3 COMMENTS

- @assignment.comments.each do |c|
	= "#{c.content} -"
	%a{href: "/users/#{c.user.id}"} #{c.user.name}
	%br
	= form_for c, method: :delete do |f|
		= f.submit "x", method: :delete
%br

ADD COMMENT
= form_for @new_comment, method: :post do |f|
	= f.hidden_field :commentable_id, value: @assignment.id
	= f.hidden_field :commentable_type, value: "Assignment"
	= f.text_area :content
	%br
	= f.submit "POST"
	%br