config/routes.rb
Rails.application.routes.draw do
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  get "admin" => "admin#index"

  resources :locations
  resources :cohorts
  resources :assignments
  resources :submissions
  resources :users
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :assignments
	has_many :submissions
	has_many :comments, as: :commentable
	belongs_to :cohort

	has_secure_password
	validates_presence_of :email
	validates_uniqueness_of :email

	accepts_nested_attributes_for :comments

	# after_create :new_user_message

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_filter :ensure_logged_in, only: [:new, :create]
	def index
		@users = User.all
	end

	def new
		@new_user = User.new
	end

	def create
		@new_user = User.new(user_params)
		if @new_user.save
			# debugger
			if params[:request] == "1"
				UserMailer.new_admin_request(@new_user)
			end
			redirect_to users_path, notice: "Thanks for signing up! Now please login to confirm your new account."
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to user_path
		else
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			redirect_to users_path
		else
			redirect_to users_path
		end
	end

	def show
		@user = User.find(params[:id])
		@new_comment = @user.comments.build
	end

	private

	def user_params
		params.require(:user).permit!
	end
end

app/views/users/_form.html.haml
ASSIGNMENT
= f.select :assignment_id, Assignment.cohort.all.collect {|a| ["#{a.title}, #{a.due_date}", a.id]}
TITLE
= f.text_field :title
LINKS
= f.text_area :description
ATTACHMENT
= f.file_field :attachment
%br
%br
= f.submit "SUBMIT"

app/views/users/edit.html.haml
-@user.submissions.each do |s|
	= form_for s, url: "/users/#{@user.id}" do |f|
		= render "form", f: f

app/views/users/index.html.haml
%br
%br
- @users.each do |user|
	%a{href: "/users/#{user.id}"} #{user.name}
	%br
	= user.email
	%br
	= user.cohort.season
	= user.cohort.course
	%br
	%br

app/views/users/new.html.haml
Sign Up!
%br
= form_for @new_user, method: :post do |f|
	Name:
	= f.text_field :name
	Email:
	= f.email_field :email
	%br
	Password
	= f.password_field :password
	Password Confirmation
	= f.password_field :password_confirmation
	%br
	Cohort
	= f.select :cohort_id, Cohort.all.collect {|c| ["#{c.season}, #{c.course}", c.id]}
	Request Admin
	= check_box_tag :request
	%br
	= f.submit "Sign up"

app/views/users/show.html.haml
%h1 #{@user.name}

%h3 HOMEWORK SUBMISSIONS

-@user.submissions.each do |s|
	ASSIGNMENT:
	%a{href: "/assignments/#{s.assignment.id}"} #{s.assignment.title}
	%br
	DEADLINE:
	= s.assignment.due_date
	%br
	SUBMISSION:
	%a{href: "/submissions/#{s.id}"} #{s.title}
	%br
%br
%br

= button_to "VIEW ASSIGNMENTS", assignments_path, method: :get
= button_to "SUBMIT NEW HOMEWORK", new_submission_path, method: :get
%hr