config/routes.rb
Rails.application.routes.draw do
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  get "admin" => "admin#index"

  resources :locations
  resources :cohorts
  resources :assignments
  resources :submissions
  resources :users
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#index'

end

app/models/submission.rb
class Submission < ActiveRecord::Base
	has_many :comments, as: :commentable
	belongs_to :user
	belongs_to :assignment

	accepts_nested_attributes_for :comments
	mount_uploader :attachment, HomeworkUploader

	validates_uniqueness_of :assignment_id, scope: :user_id

	def set_user!(user)
		self.user_id = user.id

		self.save
	end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

	def index
		@submissions = Submission.all
	end

	def new
		@new_submission = Submission.new
	end

	def create
		@user = current_user
		@new_submission = Submission.new(submission_params)
		@new_submission.set_user!(current_user)
		if @new_submission.save
			redirect_to submissions_path
		else
			redirect_to :back, notice: 'Sorry, you can only submit once per assignment.'
		end
	end

	def edit
		@user = current_user
		if @user.admin == true
			@submission = Submission.find(params[:id])
		else
			redirect_to :back, notice: "Access denied.  Only admins can update homework status."
		end
	end

	def update
		@submission = Submission.find(params[:id])
		if @submission.update_attributes(submission_params)
			redirect_to submission_path
		else
			redirect_to :edit
		end
	end

	def destroy
		@submission = Submission.find(params[:id])
		if @submission.destroy
			redirect_to submissions_path
		else
			redirect_to submissions_path
		end
	end

	def show
		@user = current_user
		@submission = Submission.find(params[:id])
		if @submission.complete == true
			@status = "COMPLETE"
		elsif @submission.complete == false
			@status = "UNDER REVIEW"
		else
			@status = "INCOMPLETE"
		end
			
		if @user.admin == true || @user.id == @submission.user.id
			@new_comment = Comment.new
		else
			redirect_to submissions_path, notice: "Access denied.  Only administrators may view submissions."
		end
	end

	private

	def submission_params
		params.require(:submission).permit(:title, :description, :assignment_id, :user_id, :attachment, :submission_date, :created_at, :updated_at, :reviewing, :complete, commentable_attributes:[:content])
	end

end

app/views/submissions/edit.html.haml
= form_for @submission, method: :put do |f|
	%br
	%h3 HOMEWORK STATUS

	%br
	UNDER REVIEW
	= f.radio_button :complete, false
	COMPLETE
	= f.radio_button :complete, true
	%br
	%br
	= f.submit "SUBMIT"

app/views/submissions/index.html.haml
- @submissions.each do |s|
	%a{href: "/submissions/#{s.id}"} #{s.title}

app/views/submissions/new.html.haml
%h3 SUBMIT ASSIGNMENT

= form_for Submission.new, method: :post do |f|
	ASSIGNMENT
	= f.select :assignment_id, Assignment.all.collect {|a| ["#{a.title}, #{a.due_date}", a.id]}
	TITLE
	= f.text_field :title
	LINKS
	= f.text_area :description
	ATTACHMENT
	= f.file_field :attachment
	%br
	%br
	= f.submit "SUBMIT"

app/views/submissions/show.html.haml
= @submission.user.name
%br
= @submission.title
%br
= @submission.description
%br
%br
%h3 STATUS: #{@status}

%h3 EDIT SUBMISSION

= form_for @submission, method: :put do |f|
	ASSIGNMENT
	= f.select :assignment_id, Assignment.all.collect {|a| ["#{a.title}, #{a.due_date}", a.id]}
	TITLE
	= f.text_field :title
	LINKS
	= f.text_area :description
	ATTACHMENT
	= f.file_field :attachment
	%br
	= f.submit "SAVE CHANGES"
%br
(ADMIN ONLY)
= button_to "UPDATE STATUS", edit_submission_path, method: :get
%br
%hr
%h3 COMMENTS

- @submission.comments.each do |c|
	%br
	= "#{c.content} -"
	%a{href: "/users/#{c.user.id}"} #{c.user.name}
	%br
	= form_for c, method: :delete do |f|
		= f.submit "x", method: :delete
%br

ADD COMMENT
= form_for @new_comment, method: :post do |f|
	= f.hidden_field :commentable_id, value: @submission.id
	= f.hidden_field :commentable_type, value: "Submission"
	= f.text_area :content
	%br
	= f.submit "POST"
	%br