config/routes.rb
Rails.application.routes.draw do
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  get "admin" => "admin#index"

  resources :locations
  resources :cohorts
  resources :assignments
  resources :submissions
  resources :users
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :cohorts
	has_many :users, through: :cohorts
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	def index
		@locations = Location.all
	end

	def new
		@user = current_user
		if @user.admin == true
			@new_location = Location.new
		else
			redirect_to :back, notice: "Sorry, only admins have permission to add locations."
		end
	end

	def create
		@new_location = Location.new(location_params)
		if @new_location.save
			redirect_to locations_path
		else
			redirect_to :new
		end
	end

	def edit
		@location = Location.find(params[:id])
	end

	def update
		@location = Location.find(params[:id])
		if @location.update_attributes(location_params)
			redirect_to locations_path
		else
			redirect_to :edit
		end
	end

	def destroy
		@location = Location.find(params[:id])
		if @location.destroy
			redirect_to locations_path
		else
			redirect_to locations_path
		end
	end

	def show
		@location = Location.find(params[:id])
	end

	private

	def location_params
		params.require(:location).permit!
	end

end

app/views/locations/index.html.haml
%br
%h3 ACTIVE LOCATIONS
%br
- @locations.each do |location|
	%a{href: "/locations/#{location.id}"} #{location.city}, #{location.state}
	%br
%br


= button_to "ADD LOCATION", new_location_path, method: :get

app/views/locations/new.html.haml
%h3 ADD NEW LOCATION
= form_for Location.new, method: :post do |f|
	CITY:
	= f.text_field :city
	STATE:
	= f.text_field :state
	ZIP:
	= f.text_field :zip
	ADDRESS:
	= f.text_field :address
	%br
	%br
	= f.submit "SUBMIT LOCATION"

app/views/locations/show.html.haml
%h1 #{@location.city}, #{@location.state}

%h3 ACTIVE COHORTS
- @location.cohorts.each do |c|
	%a{href: "/cohorts/#{c.id}"} #{c.season}, #{c.course}
	%br
%br
%br
EDIT LOCATION
= form_for @location, method: :put do |f|
	CITY:
	= f.text_field :city
	STATE:
	= f.text_field :state
	ZIP:
	= f.text_field :zip
	ADDRESS:
	= f.text_field :address
	%br
	%br
	= f.submit "SUBMIT LOCATION"

	= form_for @location, method: :delete do |f|
		= f.submit "REMOVE LOCATION", method: :delete